(lambda (secret)
  (map (lambda (query)
         (if (eq? (car query) '*step*)
             `(*step* ,secret)
             `(*local* ,secret ,query)))
       `((ledger-index)
         (ontology-insert! (ref (s1)) (ref (p1)) (ref (o1)))
         (ontology-insert! (ref (s1)) (ref (p1)) (ref (o2)))
         (ontology-insert! (ref (s1)) (ref (p1)) (ref (o3)))
         (ontology-insert! (ref (s1)) (ref (p1)) (var))
         (ontology-insert! (ref (s1)) (ref (p2)) (exp (+ 2 2)))
         (ontology-remove! (ref (s1)) (ref (p1)) (ref (o1)))
         (*step*)
         (ontology-select (ref (s1)) (ref (p1)) (var))
         (ontology-select (ref (s1)) (ref (p2)) (var))
         (ontology-remove! (ref (s1)) (ref (p2)) (exp (+ 2 2)))
         (*step*)
         (ontology-select (ref (s1)) (ref (p2)) (var))
         (ontology-select (ref (s1)) (ref (p2)) (var) #f -2)
         (ontology-insert! (ref (s1)) (ref (p2)) (exp (+ 4 4)) (*state* my-ontology))
         (ontology-insert! (ref (s1)) (ref (p2)) (exp (+ 8 8)) (*state* my-ontology))
         (*step*)
         (ontology-select (var) (var) (var) (*state* my-ontology))
         )))
