(lambda (run-test make-messenger control-src standard-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) #t)))
         (query (lambda (x)
                  `(,(car x)
                    (*call* ,(pass (car x))
                            (lambda (root)
                              (let* ((std-node (cadr ((root 'get) '(control library standard))))
                                     (std ((eval (byte-vector->expression (sync-car std-node))) std-node)))
                                ,(cadr x))))
                    ,@(cddr x)))))
    (run-test
     (append
      (map init '(journal))
      (map install `((journal ,standard-src "Installed standard library")))
      (map query
           `((journal ((root 'set!) '(control test source)
                       `(content ,((std 'dump) std) (lambda (x) (eq? (car x) 'sync-node)))) #t)
             (journal ((root 'set!) '(control test stateful)
                       `(content ,(((std 'make) '(define-class (foo)
                                                   (define (add self x) (+ x 1))
                                                   (define* (fact self x (result 1))
                                                     (if (< x 1) result
                                                         ((self 'fact) (- x 1) (* result x))))
                                                   (define (state-get self)
                                                     (byte-vector->expression (sync-cdr (self))))
                                                   (define (state-set! self x)
                                                     (set! (self) (sync-cons (sync-car (self))
                                                                             (expression->byte-vector x))))))))) #t)
             (journal (let ((object ((std 'load) (cadr ((root 'get) '(control test stateful))))))
                        ((object 'add) 1)) 2)
             (journal (let ((object ((std 'load) (cadr ((root 'get) '(control test stateful))))))
                        ((object 'fact) 4)) (* 4 3 2 1))
             (journal (let ((object ((std 'load) (cadr ((root 'get) '(control test stateful))))))
                        ((object 'state-set!) "hello, world!")
                        ((root 'set!) '(control test stateful) `(content ,((std 'dump) object)))) #t)
             (journal (let ((object ((std 'load) (cadr ((root 'get) '(control test stateful))))))
                        ((object 'state-get))) "hello, world!")
             (journal (let* ((object ((std 'load) (cadr ((root 'get) '(control test stateful)))))
                             (query '(lambda (node)
                                       (let ((object ((eval (byte-vector->expression (sync-car node))) node)))
                                         ((object 'state-set!) 5)
                                         ((object 'state-get)))))
                             (serialized ((std 'serialize) (object) query))
                             (deserialized ((std 'deserialize) serialized)))
                        ((eval query) deserialized)) 5)
             (journal (let ((object-1 ((std 'make) '(define-class (class-1)
                                                       (define (get self ~index)
                                                         (self '(1)))
                                                       (define (set! self ~index value)
                                                         (set! (self '(1)) value)))))
                            (object-2 ((std 'make) '(define-class (class-2)
                                                       (define (*init* self)
                                                         (set! (self '(1)) (sync-cons (sync-null) (sync-null))))
                                                       (define (get self index)
                                                         (self `(1 ,index)))
                                                       (define (set! self index value)
                                                         (set! (self `(1 ,index)) value)))))
                            (object-3 ((std 'make) '(define-class (class-3)
                                                      (define (*init* self)
                                                        (set! (self '(1)) (expression->byte-vector 0)))
                                                      (define (read self)
                                                        (byte-vector->expression (self '(1))))
                                                      (define (increment self)
                                                        (let ((previous (byte-vector->expression (self '(1)))))
                                                          (set! (self '(1)) (expression->byte-vector (+ previous 1)))))))))
                        ((object-2 'dset!) 1 (object-3))
                        ((object-1 'dset!) "some path" (object-2))
                        ((std 'deep-call) object-1 '("some path" 1) (lambda (obj) ((obj 'increment))))
                        ((std 'deep-call) object-1 '("some path" 1) (lambda (obj) ((obj 'increment))))
                        ((std 'deep-call) object-1 '("some path" 1) (lambda (obj) ((obj 'read))))
                        ) (lambda (x) (and (= (car x) 2) (eq? (caadr x) 'sync-node))))
             ))))))
