(lambda (secret)
  (map (lambda (query)
         (if (eq? (car query) '*step*)
             `(*step* ,secret)
             `(*local* ,secret ,query)))
       `((ledger-index)
         (ontology-clip-set! rdf "http://w3.id/rdf")
         (ontology-clip-get rdf)
         (ontology-clip-all)
         (ontology-insert! (ref (s1)) (ref (p1)) (ref (o1)))
         (ontology-insert! (ref (s1)) (ref (p1)) (ref (o2)))
         (ontology-insert! (ref (s1)) (ref (p1)) (ref (o3)))
         (ontology-insert! (ref (s1)) (ref (p1)) (var))
         (ontology-insert! (ref (s1)) (ref (p2)) (exp (+ 2 2)))
         (ontology-remove! (ref (s1)) (ref (p1)) (ref (o1)))
         (*step*)
         (ontology-select (ref (s1)) (ref (p1)) (var))
         (ontology-select (ref (s1)) (ref (p2)) (var)))))
