(lambda (run-test make-messenger control-src standard-src linear-chain-src log-chain-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) ,(caddr x))))
         (query (lambda (x)
                  `(,(car x)
                    (*call* ,(pass (car x))
                            (lambda (root)
                              (let* ((std-node (cadr ((root 'get) '(control library standard))))
                                     (std ((eval (byte-vector->expression (sync-car std-node))) std-node)))
                                ,(cadr x))))
                    ,@(cddr x))))
         (queries (lambda (chain)
                    (map query
                         `((journal (let ((chain ((std 'make) (cadr ((root 'get) '(control library ,chain))))))
                                      ((root 'set!) '(control test chain-1) `(object ,((std 'dump) chain)))) #t)
                           (journal (let ((chain ((std 'load) (cadr ((root 'get) '(control test chain-1))))))
                                      ((chain 'size))) 0)
                           (journal (let ((chain ((std 'load) (cadr ((root 'get) '(control test chain-1))))))
                                      ((chain 'push!) (expression->byte-vector "hello"))
                                      ((chain 'push!) (expression->byte-vector ","))
                                      ((chain 'push!) (expression->byte-vector "world"))
                                      ((chain 'push!) (expression->byte-vector "!"))
                                      ((root 'set!) '(control test chain-1) `(object ,(chain)))) #t)
                           (journal (let ((chain ((std 'load) (cadr ((root 'get) '(control test chain-1))))))
                                      (list (byte-vector->expression ((chain 'get) 0))
                                            (byte-vector->expression ((chain 'get) 1))
                                            (byte-vector->expression ((chain 'get) 2))
                                            (byte-vector->expression ((chain 'get) 3))
                                            )) '("hello" "," "world" "!"))
                           (journal (let ((chain ((std 'load) (cadr ((root 'get) '(control test chain-1))))))
                                      ((chain 'set!) 1 (expression->byte-vector ":"))
                                      (byte-vector->expression ((chain 'get) 1))) ":")
                           (journal (let ((chain ((std 'load) (cadr ((root 'get) '(control test chain-1))))))
                                      ((chain 'truncate!) 1)
                                      (byte-vector->expression ((chain 'get) -1))) "!")
                           (journal (let ((chain-1 ((std 'load) (cadr ((root 'get) '(control test chain-1)))))
                                          (chain-2 ((std 'load) (cadr ((root 'get) '(control test chain-1)))))
                                          (chain-3 ((std 'load) (cadr ((root 'get) '(control test chain-1))))))
                                      ((chain-2 'push!) (expression->byte-vector "this"))
                                      ((chain-2 'push!) (expression->byte-vector "is"))
                                      ((chain-3 'push!) (expression->byte-vector "this"))
                                      ((chain-3 'push!) (expression->byte-vector "is"))
                                      ((chain-3 'push!) (expression->byte-vector "a"))
                                      ((chain-3 'push!) (expression->byte-vector "somewhat"))
                                      ((chain-3 'push!) (expression->byte-vector "longer"))
                                      ((chain-3 'push!) (expression->byte-vector "chain"))
                                      (and (equal? ((chain-1 'digest)) ((chain-2 'digest) -3))
                                           (equal? ((chain-1 'digest)) ((chain-3 'digest) -7)))) #t)
                           )))))
    (run-test
     (append
      (map init '(journal))
      (map install `((journal ,standard-src "Installed standard library")
                     (journal ,linear-chain-src "Installed linear chain class")
                     (journal ,log-chain-src "Installed log chain class")
                     ))
      (queries 'linear-chain)
      (queries 'log-chain)
      ))))
