(lambda (run-test make-messenger control-src standard-src chain-src record-src ledger-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) #t)))
         (query (lambda (x) `(,(car x)
                              ,(if (eq? (cadr x) '*step*) `(*step* ,(pass (car x)))
                                   (cadr x))
                              ,@(cddr x)))))
    (run-test
     (append
      (map init '(journal-1 journal-2 journal-3))
      (map install `((journal-1 ,standard-src) (journal-1 ,chain-src) (journal-1 ,record-src)
                     (journal-2 ,standard-src) (journal-2 ,chain-src) (journal-2 ,record-src)
                     (journal-3 ,standard-src) (journal-3 ,chain-src) (journal-3 ,record-src)
                     (journal-1 (,ledger-src ,(pass 'journal-1) #f 2 10))
                     (journal-2 (,ledger-src ,(pass 'journal-2) #f 2 10))
                     (journal-3 (,ledger-src ,(pass 'journal-3) #f 2 10))))
      (map query
           `((journal-1 *step* '((0 1)))
             (journal-1 (ledger-set! (*state* do pin this) (content yes)) #t)
             (journal-1 (ledger-set! (*state* do pin that) (content yes)) #t)
             (journal-1 (ledger-set! (*state* do not pin) (content no)) #t)
             (journal-1 *step*)
             (journal-1 *step*)
             (journal-1 (ledger-get (*state* do pin)) '(directory (this that) #t))
             (journal-1 (ledger-get (*state* do pin) 2) '(directory (this that) #t))
             (journal-1 (ledger-pin! (*state* do pin this) 2) #t)
             (journal-1 (ledger-pin! (*state* do pin that) 2) #t)
             (journal-1 (ledger-get (*state* do pin) 2))
             (journal-1 (ledger-peer! journal-2 ,(make-messenger 'journal-2)) #t)
             (journal-1 (ledger-peer! journal-3 blah) (lambda (r) (eq? (car r) 'error)))
             (journal-1 (ledger-peer! journal-3 #f) #t)
             (journal-2 *step*)
             (journal-2 (ledger-set! (*state* a b c) (content 42)) #t)
             (journal-2 (ledger-set! (*state* a b c*) (content 43)) #t)
             (journal-2 (ledger-copy! (*state* a b c*) (*state* a b c**)) #t)
             (journal-2 *step*)
             (journal-2 (ledger-get (*state* a b c*)) '(content 43))
             (journal-2 (ledger-get (*state* a b c**)) '(content 43))
             (journal-1 *step*)
             (journal-2 *step*)
             (journal-2 (ledger-pin! (*state* a b c) 2) #t)
             (journal-1 *step*)
             (journal-2 *step*)
             (journal-1 *step*)
             (journal-2 *step*)
             (journal-2 (ledger-set! (*state* a b c) (content 44)) #t)
             (journal-2 *step*)
             (journal-1 *step*)
             (journal-1 *step*)
             (journal-2 *step*)
             (journal-1 (ledger-index))
             ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b)) '(directory (c c** c*) #t))
             ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b c) 6) '(object 44))
             ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b c)) '(object 44))
      ;; (journal-2 (ledger-peer! journal-3 ,(make-messenger 'journal-3)) #t)
      ;; (journal-3 (ledger-peer! ledger-4 ,(make-messenger 'ledger-4)) #t)
      ;; (journal-3 (ledger-peer! ledger-5 ,(make-messenger 'ledger-5)) #t)
      ;; (journal-3 (ledger-set! (*state* d e f) 64) #t)
      ;; (ledger-4 (ledger-set! (*state* g h i) "hello") #t)
      ;; (ledger-5 (ledger-set! (*state* g h i) "world") #t)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-2 (ledger-get (*peers* journal-3 *state* d e f)) `(object 64))
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-1 (ledger-get (*peers* journal-2 *peers* journal-3 *state* d e f)) '(object 64))
      ;; (journal-1 (ledger-get (*peers* journal-2 *peers* journal-3 *peers* ledger-4 *state* g h i)) '(object "hello"))
      ;; (journal-1 (ledger-get (*peers* journal-2 *peers* journal-3 *peers* ledger-5 *state* g h i)) '(object "world"))
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 (ledger-index))
      ;; (journal-1 (ledger-get (*state* do pin) 2) '(directory (this that) #t))
      ;; (journal-1 (ledger-get (*state* do pin this) 2) '(object yes))
      ;; (journal-1 (ledger-get (*state* do pin that) 2) '(object yes))
      ;; (journal-1 (ledger-get (*state* do not pin) 2) '(nothing ()))
      ;; (journal-1 (ledger-unpin! (*state* do pin that) 2) #t)
      ;; (journal-1 (ledger-get (*state* do pin) 2))
      ;; (journal-1 (ledger-get (*state* do pin this) 2) '(object yes))
      ;; (journal-1 (ledger-get (*state* do pin that) 2) '(nothing ()))
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b c) 4) '(object 42))
      ))
      ))))
