(lambda (run-test make-messenger control-src standard-src chain-src record-src config-src ledger-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) #t)))
         (setup (lambda (args)
                  (let ((journal-name (car args))
                        (obj-name (cadr args)))
                    `(,journal-name
                      (*call* ,(pass journal-name)
                              (lambda (root)
                                (let* ((std-node (cadr ((root 'get) '(control library standard))))
                                       (standard ((eval (byte-vector->expression (sync-car std-node))) std-node))
                                       (config-class (cadr ((root 'get) '(control class configuration))))
                                       (record-class (cadr ((root 'get) '(control class record))))
                                       (chain-class (cadr ((root 'get) '(control class chain))))
                                       (ledger-class (cadr ((root 'get) '(control class ledger))))
                                       (keys (crypto-generate (expression->byte-vector ,(pass journal-name))))
                                       (config-expr `((public ((window 10)
                                                               (public-key ,(car keys))))
                                                      (private ((secret-key ,(cdr keys))
                                                                (record-class ,record-class)
                                                                (chain-class ,chain-class)))))
                                       (config ((standard 'make) config-class `(,config-expr)))
                                       (ledger ((standard 'make) ledger-class `(,standard ,config)))
                                       (handler '(lambda (root query)
                                                   (let* ((node (cadr ((root 'get) `(control test ,(caar query)))))
                                                          (obj ((eval (byte-vector->expression (sync-car node))) node))
                                                          (res (if (eq? (cadr (cadar query)) '*step-all-test*)
                                                                   (let loop ((sub ((obj 'step-generate))) (results '()))
                                                                     (if (null? sub) (reverse results)
                                                                         (let ((r (apply (obj (caar sub)) (cdar sub))))
                                                                           (loop (cdr sub) (cons r results)))))
                                                                   (let* ((proc (lambda (x) (if (list? x) (cadr x) x)))
                                                                          (args (map proc (cdr query))))
                                                                     (apply (obj (cadr (cadar query))) args)))))
                                                     ((root 'set!) `(control test ,(caar query)) `(content ,(obj))) res))))
                                  ((root 'set!) '(control endpoint test) `(content ,handler))
                                  ((root 'set!) '(control test ,obj-name) `(content ,(ledger)))))) #t))))
         (peer (lambda (name)
                 (let ((keys (crypto-generate (expression->byte-vector (pass name))))
                       (messenger (make-messenger name)))
                   `((public-key ,(car keys))
                     (synchronize (lambda (index) (,messenger `(test ((ledger 'synchronize) ,index)))))
                     (resolve (lambda (path) (,messenger `(test ((ledger 'resolve) ,path)))))))))
         (query (lambda (args)
                  (let ((journal-name (car args))
                        (query~ (cadr args))
                        (test (if (null? (cddr args)) #t (caddr args))))
                    `(,journal-name (test ,query~) ,test)))))
    (run-test
     (append
      (map init '(journal-1 journal-2 journal-3))
      (map install `((journal-1 (,standard-src '(control library standard)))
                     (journal-2 (,standard-src '(control library standard)))
                     (journal-3 (,standard-src '(control library standard)))
                     (journal-1 (,record-src '(control class record)))
                     (journal-2 (,record-src '(control class record)))
                     (journal-3 (,record-src '(control class record)))
                     (journal-1 (,chain-src '(control class chain)))
                     (journal-2 (,chain-src '(control class chain)))
                     (journal-3 (,chain-src '(control class chain)))
                     (journal-1 (,config-src '(control class configuration)))
                     (journal-2 (,config-src '(control class configuration)))
                     (journal-3 (,config-src '(control class configuration)))
                     (journal-1 (,ledger-src '(control class ledger)))
                     (journal-2 (,ledger-src '(control class ledger)))
                     (journal-3 (,ledger-src '(control class ledger)))))
      (map setup '((journal-1 ledger) (journal-2 ledger) (journal-3 ledger)))
      (map query
           `(
             (journal-1 ((ledger 'size)) 0)
             (journal-1 ((ledger '*step-all-test*)) '(1))
             (journal-1 ((ledger 'set!) '((*state* do pin this)) '(content "yes")) #t)
             (journal-1 ((ledger 'set!) '((*state* do pin that)) '(content "yes")) #t)
             (journal-1 ((ledger 'set!) '((*state* do not pin)) '(content "no")) #t)
             (journal-1 ((ledger 'get) '((*state* do not pin))) '(content "no"))
             (journal-1 ((ledger 'get) '((*state* do pin))) '(directory (this that) #t))
             (journal-1 ((ledger '*step-all-test*)) '(2))
             (journal-1 ((ledger '*step-all-test*)) '(3))
             (journal-1 ((ledger 'get) '(-1 (*state* do pin this))) '(content "yes"))
             (journal-1 ((ledger 'get) '(-2 (*state* do pin that))) '(content "yes"))
             (journal-1 ((ledger 'pin!) '(2 (*state* do pin this))) #t)
             (journal-1 ((ledger 'pin!) '(2 (*state* do pin that))) #t)
             (journal-1 ((ledger 'get) '(2 (*state* do pin))) '(directory (this that) #t))
             (journal-1 ((ledger 'peer!) 'journal-2 ',(peer 'journal-2)) #t)
             (journal-1 ((ledger 'peer!) 'journal-ignore '("ignore me")) #t)
             (journal-1 ((ledger 'peers)) '(journal-2 journal-ignore))
             (journal-1 ((ledger 'peer!) 'journal-ignore '()) #t)
             (journal-1 ((ledger 'peers)) '(journal-2))
             (journal-1 ((ledger '*step-all-test*)) '(4 #t))
             ;; (journal-2 (ledger-set! (*state* a b c) (content 42)) #t)
             ;; (journal-2 (ledger-set! (*state* a b c*) (content 43)) #t)
             ;; (journal-2 (ledger-copy! (*state* a b c*) (*state* a b c**)) #t)
             ;; (journal-2 *step*)
             ;; (journal-2 (ledger-get (*state* a b c*)) '(content 43))
             ;; (journal-2 (ledger-get (*state* a b c**)) '(content 43))
             ;; (journal-1 *step*)
             ;; (journal-2 *step*)
             ;; (journal-2 (ledger-pin! (*state* a b c) 2) #t)
             ;; (journal-1 *step*)
             ;; (journal-2 *step*)
             ;; (journal-1 *step*)
             ;; (journal-2 *step*)
             ;; (journal-2 (ledger-set! (*state* a b c) (content 44)) #t)
             ;; (journal-2 *step*)
             ;; (journal-1 *step*)
             ;; (journal-1 *step*)
             ;; (journal-2 *step*)
             ;; (journal-1 (ledger-index))
             ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b)) '(directory (c c** c*) #t))
             ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b c) 6) '(object 44))
             ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b c)) '(object 44))
      ;; (journal-2 (ledger-peer! journal-3 ,(make-messenger 'journal-3)) #t)
      ;; (journal-3 (ledger-peer! ledger-4 ,(make-messenger 'ledger-4)) #t)
      ;; (journal-3 (ledger-peer! ledger-5 ,(make-messenger 'ledger-5)) #t)
      ;; (journal-3 (ledger-set! (*state* d e f) 64) #t)
      ;; (ledger-4 (ledger-set! (*state* g h i) "hello") #t)
      ;; (ledger-5 (ledger-set! (*state* g h i) "world") #t)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-2 (ledger-get (*peers* journal-3 *state* d e f)) `(object 64))
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-3 *step*)
      ;; (ledger-4 *step*)
      ;; (ledger-5 *step*)
      ;; (journal-1 (ledger-get (*peers* journal-2 *peers* journal-3 *state* d e f)) '(object 64))
      ;; (journal-1 (ledger-get (*peers* journal-2 *peers* journal-3 *peers* ledger-4 *state* g h i)) '(object "hello"))
      ;; (journal-1 (ledger-get (*peers* journal-2 *peers* journal-3 *peers* ledger-5 *state* g h i)) '(object "world"))
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 (ledger-index))
      ;; (journal-1 (ledger-get (*state* do pin) 2) '(directory (this that) #t))
      ;; (journal-1 (ledger-get (*state* do pin this) 2) '(object yes))
      ;; (journal-1 (ledger-get (*state* do pin that) 2) '(object yes))
      ;; (journal-1 (ledger-get (*state* do not pin) 2) '(nothing ()))
      ;; (journal-1 (ledger-unpin! (*state* do pin that) 2) #t)
      ;; (journal-1 (ledger-get (*state* do pin) 2))
      ;; (journal-1 (ledger-get (*state* do pin this) 2) '(object yes))
      ;; (journal-1 (ledger-get (*state* do pin that) 2) '(nothing ()))
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 *step*)
      ;; (journal-2 *step*)
      ;; (journal-1 (ledger-get (*peers* journal-2 *state* a b c) 4) '(object 42))
      ))
      ))))
