;; use this to load/coordinate things

;; question is ledger unique because it requires network operations? maybe...
;; weird singleton pattern that I don't really like...
;; maybe chains need to transparently pass along gets?
;; ledger is doing too much right now...
;; oooh should we have some kind of "network" object?
;; - contract between local peer and remote peer
